# <font color=darkblue> Machine Learning model deployment with Flask framework</font>

## <font color=Blue>Used Cars Price Prediction Application</font>

### Objective:
1. To build a Machine learning regression model to predict the selling price of the used cars based on the different input features like fuel_type, kms_driven, type of transmission etc.
2. Deploy the machine learning model with the help of the flask framework.

### Dataset Information:
#### Dataset Source: https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho?select=CAR+DETAILS+FROM+CAR+DEKHO.csv
This dataset contains information about used cars listed on www.cardekho.com
- **Car_Name**: Name of the car
- **Year**: Year of Purchase
- **Selling Price (target)**: Selling price of the car in lakhs
- **Present Price**: Present price of the car in lakhs
- **Kms_Driven**: kilometers driven
- **Fuel_Type**: Petrol/diesel/CNG
- **Seller_Type**: Dealer or Indiviual
- **Transmission**: Manual or Automatic
- **Owner**: first, second or third owner


### 1. Import required libraries

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

### 2. Load the dataset

In [19]:
df = pd.read_csv('car+data.csv')
df.head(5)

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

### 3. Check the shape and basic information of the dataset.

In [20]:
## check the shape
df.shape

(301, 9)

In [21]:
## check basic information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


### 4. Check for the presence of the duplicate records in the dataset? If present drop them

In [23]:
# checking number of duplicate records
len(df[df.duplicated()])

2

In [24]:
# Dropping the duplicate records
df = df.drop_duplicates()

In [25]:
# checking the length after dropping duplicate records
len(df[df.duplicated()])

0

### 5. Drop the columns which you think redundant for the analysis.

In [26]:
# dropping columns which are redundant for analysis
df.drop(['Car_Name'],axis=1, inplace=True)

In [27]:
df.head(2)

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   
1  2013           4.75           9.54       43000    Diesel      Dealer   

  Transmission  Owner  
0       Manual      0  
1       Manual      0

### 6. Extract a new feature called 'age_of_the_car' from the feature 'year' and drop the feature year

In [28]:
# subtracting the year of purchase with current year to get age of car
df['age_of_the_car'] = 2022-df['Year']

In [29]:
# dropping column year
df = df.drop('Year', axis=1)

In [30]:
df.head(2)

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0           3.35           5.59       27000    Petrol      Dealer   
1           4.75           9.54       43000    Diesel      Dealer   

  Transmission  Owner  age_of_the_car  
0       Manual      0               8  
1       Manual      0               9

### 7. Encode the categorical columns

In [31]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [32]:
df['Seller_Type'].unique()

array(['Dealer', 'Individual'], dtype=object)

In [33]:
df['Transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [34]:
## Manual encoding:
df['Fuel_Type'] = df['Fuel_Type'].replace({'Petrol':0, 'Diesel':1,'CNG':2})
df['Seller_Type'] = df['Seller_Type'].replace({'Dealer':0, 'Individual':1})
df['Transmission'] = df['Transmission'].replace({'Manual':0, 'Automatic':1})

In [35]:
df['Fuel_Type'].unique()

array([0, 1, 2], dtype=int64)

In [36]:
df['Seller_Type'].unique()

array([0, 1], dtype=int64)

In [37]:
df['Transmission'].unique()

array([0, 1], dtype=int64)

### 8. Separate the target and independent features.

In [38]:
X = df.drop('Selling_Price', axis=1)
y = df['Selling_Price']

### 9. Split the data into train and test.

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

print(X_train.shape,X_test.shape)
print(y_train.shape,y_test.shape)

### 10. Build a Random forest Regressor model and check the r2-score for train and test.

In [ ]:
# Build a Random Forest Regressor model
rfr = RandomForestRegressor() 

# Fit the model to the training data
rfr.fit(X_train, y_train)

In [ ]:
# Predict on the training and testing data
y_train_pred = rfr.predict(X_train)
y_test_pred = rfr.predict(X_test)

# Calculate the R-squared score for the training and testing data
r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

# Print the R-squared scores
print("R-squared score for training data:", r2_train)
print("R-squared score for testing data:", r2_test)

### 11. Create a pickle file with an extension as .pkl

In [ ]:
import pickle
# Saving model to disk
pickle.dump(rfr, open('model.pkl','wb'))

### 12. Create new folder/new project in visual studio/pycharm that should contain the "model.pkl" file *make sure you are using a virutal environment and install required packages.*

### a) Create a basic HTML form for the frontend

Create a file **index.html** in the templates folder and copy the following code.

In [ ]:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>ML Deployment</title>
    <link
      href="https://fonts.googleapis.com/css?family=Pacifico"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Arimo"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Hind:300"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300"
      rel="stylesheet"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
  </head>
  <body>
    <div class="login">
      <h1>Car Price Predictor</h1>
      <form action="{{ url_for('predict')}}" method="post">
        <h2>Enter Car Details:</h2>
        <br />

        <h3>Age of car in (In Years)</h3>
        <input
          id="first"
          type="number"
          name="Age_of_the_car"
          placeholder="Enter Age of car"
          required="required"
        />
        <br />
        <h3>Present showroom Price (In lakhs)</h3>

        <input
          id="second"
          name="Present_Price"
          required="required"
          placeholder="Enter showroom price"
        />
        <br />
        <h3>Kilometers Driven</h3>
        <input
          id="third"
          name="Kms_Driven"
          required="required"
          placeholder="Enter Kms Driven"
        />

        <h3>Owner Type (0/1/3)</h3>

        <input
          id="fourth"
          name="Owner"
          required="required"
          placeholder="Enter Owner Type"
        />
        <br />
        <h3>Fuel Type</h3>

        <select name="Fuel_Type" id="fuel" required="required">
          <option value="0">Petrol</option>
          <option value="1">Diesel</option>
          <option value="2">CNG</option>
        </select>
        <br />
        <h3>Seller Type</h3>

        <select name="Seller_Type" id="resea" required="required">
          <option value="0">Dealer</option>
          <option value="1">Individual</option>
        </select>
        <br />
        <h3>Transmission Type</h3>

        <select name="Transmission" id="research" required="required">
          <option value="0">Manual Car</option>
          <option value="1">Automatic Car</option>
        </select>

        <br />
        <br />
        <br />
        <button type="submit" class="btn btn-primary btn-block btn-large">
          Predict
        </button>
      </form>
      <br />
      <br />
      <div class="pred-text">{{ prediction_text }}</div>
    </div>
  </body>
</html>

### b) Create app.py file and write the predict function

In [ ]:
# importing necessary libraries and functions
import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
import sklearn

#Initializing the flask App
app = Flask(__name__) 
# loading the trained model
model = pickle.load(open('model.pkl', 'rb')) 

# Homepage
@app.route('/', methods=['GET']) 
def Home():
    return render_template('index.html')

# Predicting car price
@app.route('/predict',methods=['POST'])
def predict():
    if request.method == 'POST':
        Present_Price=float(request.form['Present_Price'])
        Kms_Driven=int(request.form['Kms_Driven'])
        Owner=int(request.form['Owner'])
        Fuel_Type=request.form['Fuel_Type']
        Age_of_the_car=request.form['Age_of_the_car']
        Seller_Type=request.form['Seller_Type']
        Transmission=request.form['Transmission']

        prediction=model.predict([[Present_Price, Kms_Driven, Owner, Age_of_the_car, Fuel_Type, Seller_Type, Transmission]])
        output= round(prediction[0],2)
        return render_template('index.html', prediction_text="You can sell your car at {} lakhs". format(output))

if __name__ == "__main__":
    app.run(debug=True)

### 13. Run the app.py python file which will render to index html page then enter the input values and get the prediction.

In [ ]:
http://127.0.0.1:5000

### Happy Learning :)